name: Build images (gh actions)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-clowarden-dbmigrator-image:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Setup for Docker cross-builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push clowarden server image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: database/migrations
          file: database/migrations/Dockerfile
          push: true
          tags: ghcr.io/jaronoff97/clowarden/clowarden-dbmigrator:${{ github.sha }}

  build-clowarden-server-image:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Setup for Docker cross-builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push clowarden server image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: clowarden-server
          file: clowarden-server/Dockerfile
          push: true
          tags: ghcr.io/jaronoff97/clowarden/clowarden-server:${{ github.sha }}
